//
//  mapi.swift
//  TNEFDecode
//
//  Created by Preston Kemp on 2/10/20.
//  Copyright © 2020 Preston Kemp. All rights reserved.
//

import Foundation

struct MAPIAttribute {
    var type:Int
    var name:Int
    var data:[Data]
    var guid:Int
    
    
}


let mvFlag = 0x1000 // OR with type means multiple values

//szmapiUnspecified   = 0x0000 //# MAPI Unspecified
//szmapiNull          = 0x0001 //# MAPI null property
let szmapiShort         = 0x0002 //# MAPI short (signed 16 bits)
let szmapiInt           = 0x0003 //# MAPI integer (signed 32 bits)
let szmapiFloat         = 0x0004 //# MAPI float (4 bytes)
let szmapiDouble        = 0x0005 //# MAPI double
let szmapiCurrency      = 0x0006 //# MAPI currency (64 bits)
let szmapiApptime       = 0x0007 //# MAPI application time
let szmapiError         = 0x000a //# MAPI error (32 bits)
let szmapiBoolean       = 0x000b //# MAPI boolean (16 bits)
let szmapiObject        = 0x000d //# MAPI embedded object
let szmapiInt8byte      = 0x0014 //# MAPI 8 byte signed int
let szmapiString        = 0x001e //# MAPI string
let szmapiUnicodeString = 0x001f //# MAPI unicode-string (null terminated)
//szmapiPtSystime     = 0x001e //# MAPI time (after 2038/01/17 22:14:07 or before 1970/01/01 00:00:00)
let szmapiSystime = 0x0040 //# MAPI time (64 bits)
let szmapiCLSID   = 0x0048 //# MAPI OLE GUID
let szmapiBinary  = 0x0102 //# MAPI binary
//szmapiUnknown = 0x0033

let MAPIAcknowledgementMode                   = 0x0001
let MAPIAlternateRecipientAllowed             = 0x0002
let MAPIAuthorizingUsers                      = 0x0003
MAPIAutoForwardComment                    = 0x0004
MAPIAutoForwarded                         = 0x0005
MAPIContentConfidentialityAlgorithmID     = 0x0006
MAPIContentCorrelator                     = 0x0007
MAPIContentIdentifier                     = 0x0008
MAPIContentLength                         = 0x0009
MAPIContentReturnRequested                = 0x000A
MAPIConversationKey                       = 0x000B
MAPIConversionEits                        = 0x000C
MAPIConversionWithLossProhibited          = 0x000D
MAPIConvertedEits                         = 0x000E
MAPIDeferredDeliveryTime                  = 0x000F
MAPIDeliverTime                           = 0x0010
MAPIDiscardReason                         = 0x0011
MAPIDisclosureOfRecipients                = 0x0012
MAPIDlExpansionHistory                    = 0x0013
MAPIDlExpansionProhibited                 = 0x0014
MAPIExpiryTime                            = 0x0015
MAPIImplicitConversionProhibited          = 0x0016
MAPIImportance                            = 0x0017
MAPIIpmID                                 = 0x0018
MAPILatestDeliveryTime                    = 0x0019
MAPIMessageClass                          = 0x001A
MAPIMessageDeliveryID                     = 0x001B
MAPIMessageSecurityLabel                  = 0x001E
MAPIObsoletedIpms                         = 0x001F
MAPIOriginallyIntendedRecipientName       = 0x0020
MAPIOriginalEits                          = 0x0021
MAPIOriginatorCertificate                 = 0x0022
MAPIOriginatorDeliveryReportRequested     = 0x0023
MAPIOriginatorReturnAddress               = 0x0024
MAPIParentKey                             = 0x0025
MAPIPriority                              = 0x0026
MAPIOriginCheck                           = 0x0027
MAPIProofOfSubmissionRequested            = 0x0028
MAPIReadReceiptRequested                  = 0x0029
MAPIReceiptTime                           = 0x002A
MAPIRecipientReassignmentProhibited       = 0x002B
MAPIRedirectionHistory                    = 0x002C
MAPIRelatedIpms                           = 0x002D
MAPIOriginalSensitivity                   = 0x002E
MAPILanguages                             = 0x002F
MAPIReplyTime                             = 0x0030
MAPIReportTag                             = 0x0031
MAPIReportTime                            = 0x0032
MAPIReturnedIpm                           = 0x0033
MAPISecurity                              = 0x0034
MAPIIncompleteCopy                        = 0x0035
MAPISensitivity                           = 0x0036
MAPISubject                               = 0x0037
MAPISubjectIpm                            = 0x0038
MAPIClientSubmitTime                      = 0x0039
MAPIReportName                            = 0x003A
MAPISentRepresentingSearchKey             = 0x003B
MAPIX400ContentType                       = 0x003C
MAPISubjectPrefix                         = 0x003D
MAPINonReceiptReason                      = 0x003E
MAPIReceivedByEntryID                     = 0x003F
MAPIReceivedByName                        = 0x0040
MAPISentRepresentingEntryID               = 0x0041
MAPISentRepresentingName                  = 0x0042
MAPIRcvdRepresentingEntryID               = 0x0043
MAPIRcvdRepresentingName                  = 0x0044
MAPIReportEntryID                         = 0x0045
MAPIReadReceiptEntryID                    = 0x0046
MAPIMessageSubmissionID                   = 0x0047
MAPIProviderSubmitTime                    = 0x0048
MAPIOriginalSubject                       = 0x0049
MAPIDiscVal                               = 0x004A
MAPIOrigMessageClass                      = 0x004B
MAPIOriginalAuthorEntryID                 = 0x004C
MAPIOriginalAuthorName                    = 0x004D
MAPIOriginalSubmitTime                    = 0x004E
MAPIReplyRecipientEntries                 = 0x004F
MAPIReplyRecipientNames                   = 0x0050
MAPIReceivedBySearchKey                   = 0x0051
MAPIRcvdRepresentingSearchKey             = 0x0052
MAPIReadReceiptSearchKey                  = 0x0053
MAPIReportSearchKey                       = 0x0054
MAPIOriginalDeliveryTime                  = 0x0055
MAPIOriginalAuthorSearchKey               = 0x0056
MAPIMessageToMe                           = 0x0057
MAPIMessageCcMe                           = 0x0058
MAPIMessageRecipMe                        = 0x0059
MAPIOriginalSenderName                    = 0x005A
MAPIOriginalSenderEntryID                 = 0x005B
MAPIOriginalSenderSearchKey               = 0x005C
MAPIOriginalSentRepresentingName          = 0x005D
MAPIOriginalSentRepresentingEntryID       = 0x005E
MAPIOriginalSentRepresentingSearchKey     = 0x005F
MAPIStartDate                             = 0x0060
MAPIEndDate                               = 0x0061
MAPIOwnerApptID                           = 0x0062
MAPIResponseRequested                     = 0x0063
MAPISentRepresentingAddrtype              = 0x0064
MAPISentRepresentingEmailAddress          = 0x0065
MAPIOriginalSenderAddrtype                = 0x0066
MAPIOriginalSenderEmailAddress            = 0x0067
MAPIOriginalSentRepresentingAddrtype      = 0x0068
MAPIOriginalSentRepresentingEmailAddress  = 0x0069
MAPIConversationTopic                     = 0x0070
MAPIConversationIndex                     = 0x0071
MAPIOriginalDisplayBcc                    = 0x0072
MAPIOriginalDisplayCc                     = 0x0073
MAPIOriginalDisplayTo                     = 0x0074
MAPIReceivedByAddrtype                    = 0x0075
MAPIReceivedByEmailAddress                = 0x0076
MAPIRcvdRepresentingAddrtype              = 0x0077
MAPIRcvdRepresentingEmailAddress          = 0x0078
MAPIOriginalAuthorAddrtype                = 0x0079
MAPIOriginalAuthorEmailAddress            = 0x007A
MAPIOriginallyIntendedRecipAddrtype       = 0x007B
MAPIOriginallyIntendedRecipEmailAddress   = 0x007C
MAPITransportMessageHeaders               = 0x007D
MAPIDelegation                            = 0x007E
MAPITnefCorrelationKey                    = 0x007F
MAPIBody                                  = 0x1000
MAPIBodyHTML                              = 0x1013
MAPIReportText                            = 0x1001
MAPIOriginatorAndDlExpansionHistory       = 0x1002
MAPIReportingDlName                       = 0x1003
MAPIReportingMtaCertificate               = 0x1004
MAPIRtfSyncBodyCrc                        = 0x1006
MAPIRtfSyncBodyCount                      = 0x1007
MAPIRtfSyncBodyTag                        = 0x1008
MAPIRtfCompressed                         = 0x1009
MAPIRtfSyncPrefixCount                    = 0x1010
MAPIRtfSyncTrailingCount                  = 0x1011
MAPIOriginallyIntendedRecipEntryID        = 0x1012
MAPIContentIntegrityCheck                 = 0x0C00
MAPIExplicitConversion                    = 0x0C01
MAPIIpmReturnRequested                    = 0x0C02
MAPIMessageToken                          = 0x0C03
MAPINdrReasonCode                         = 0x0C04
MAPINdrDiagCode                           = 0x0C05
MAPINonReceiptNotificationRequested       = 0x0C06
MAPIDeliveryPoint                         = 0x0C07
MAPIOriginatorNonDeliveryReportRequested  = 0x0C08
MAPIOriginatorRequestedAlternateRecipient = 0x0C09
MAPIPhysicalDeliveryBureauFaxDelivery     = 0x0C0A
MAPIPhysicalDeliveryMode                  = 0x0C0B
MAPIPhysicalDeliveryReportRequest         = 0x0C0C
MAPIPhysicalForwardingAddress             = 0x0C0D
MAPIPhysicalForwardingAddressRequested    = 0x0C0E
MAPIPhysicalForwardingProhibited          = 0x0C0F
MAPIPhysicalRenditionAttributes           = 0x0C10
MAPIProofOfDelivery                       = 0x0C11
MAPIProofOfDeliveryRequested              = 0x0C12
MAPIRecipientCertificate                  = 0x0C13
MAPIRecipientNumberForAdvice              = 0x0C14
MAPIRecipientType                         = 0x0C15
MAPIRegisteredMailType                    = 0x0C16
MAPIReplyRequested                        = 0x0C17
MAPIRequestedDeliveryMethod               = 0x0C18
MAPISenderEntryID                         = 0x0C19
MAPISenderName                            = 0x0C1A
MAPISupplementaryInfo                     = 0x0C1B
MAPITypeOfMtsUser                         = 0x0C1C
MAPISenderSearchKey                       = 0x0C1D
MAPISenderAddrtype                        = 0x0C1E
MAPISenderEmailAddress                    = 0x0C1F
MAPICurrentVersion                        = 0x0E00
MAPIDeleteAfterSubmit                     = 0x0E01
MAPIDisplayBcc                            = 0x0E02
MAPIDisplayCc                             = 0x0E03
MAPIDisplayTo                             = 0x0E04
MAPIParentDisplay                         = 0x0E05
MAPIMessageDeliveryTime                   = 0x0E06
MAPIMessageFlags                          = 0x0E07
MAPIMessageSize                           = 0x0E08
MAPIParentEntryID                         = 0x0E09
MAPISentmailEntryID                       = 0x0E0A
MAPICorrelate                             = 0x0E0C
MAPICorrelateMtsID                        = 0x0E0D
MAPIDiscreteValues                        = 0x0E0E
MAPIResponsibility                        = 0x0E0F
MAPISpoolerStatus                         = 0x0E10
MAPITransportStatus                       = 0x0E11
MAPIMessageRecipients                     = 0x0E12
MAPIMessageAttachments                    = 0x0E13
MAPISubmitFlags                           = 0x0E14
MAPIRecipientStatus                       = 0x0E15
MAPITransportKey                          = 0x0E16
MAPIMsgStatus                             = 0x0E17
MAPIMessageDownloadTime                   = 0x0E18
MAPICreationVersion                       = 0x0E19
MAPIModifyVersion                         = 0x0E1A
MAPIHasattach                             = 0x0E1B
MAPIBodyCrc                               = 0x0E1C
MAPINormalizedSubject                     = 0x0E1D
MAPIRtfInSync                             = 0x0E1F
MAPIAttachSize                            = 0x0E20
MAPIAttachNum                             = 0x0E21
MAPIPreprocess                            = 0x0E22
MAPIOriginatingMtaCertificate             = 0x0E25
MAPIProofOfSubmission                     = 0x0E26
MAPIEntryID                               = 0x0FFF
MAPIObjectType                            = 0x0FFE
MAPIIcon                                  = 0x0FFD
MAPIMiniIcon                              = 0x0FFC
MAPIStoreEntryID                          = 0x0FFB
MAPIStoreRecordKey                        = 0x0FFA
MAPIRecordKey                             = 0x0FF9
MAPIMappingSignature                      = 0x0FF8
MAPIAccessLevel                           = 0x0FF7
MAPIInstanceKey                           = 0x0FF6
MAPIRowType                               = 0x0FF5
MAPIAccess                                = 0x0FF4
MAPIRowID                                 = 0x3000
MAPIDisplayName                           = 0x3001
MAPIAddrtype                              = 0x3002
MAPIEmailAddress                          = 0x3003
MAPIComment                               = 0x3004
MAPIDepth                                 = 0x3005
MAPIProviderDisplay                       = 0x3006
MAPICreationTime                          = 0x3007
MAPILastModificationTime                  = 0x3008
MAPIResourceFlags                         = 0x3009
MAPIProviderDllName                       = 0x300A
MAPISearchKey                             = 0x300B
MAPIProviderUID                           = 0x300C
MAPIProviderOrdinal                       = 0x300D
MAPIFormVersion                           = 0x3301
MAPIFormClsid                             = 0x3302
MAPIFormContactName                       = 0x3303
MAPIFormCategory                          = 0x3304
MAPIFormCategorySub                       = 0x3305
MAPIFormHostMap                           = 0x3306
MAPIFormHidden                            = 0x3307
MAPIFormDesignerName                      = 0x3308
MAPIFormDesignerGuID                      = 0x3309
MAPIFormMessageBehavior                   = 0x330A
MAPIDefaultStore                          = 0x3400
MAPIStoreSupportMask                      = 0x340D
MAPIStoreState                            = 0x340E
MAPIIpmSubtreeSearchKey                   = 0x3410
MAPIIpmOutboxSearchKey                    = 0x3411
MAPIIpmWastebasketSearchKey               = 0x3412
MAPIIpmSentmailSearchKey                  = 0x3413
MAPIMdbProvider                           = 0x3414
MAPIReceiveFolderSettings                 = 0x3415
MAPIValidFolderMask                       = 0x35DF
MAPIIpmSubtreeEntryID                     = 0x35E0
MAPIIpmOutboxEntryID                      = 0x35E2
MAPIIpmWastebasketEntryID                 = 0x35E3
MAPIIpmSentmailEntryID                    = 0x35E4
MAPIViewsEntryID                          = 0x35E5
MAPICommonViewsEntryID                    = 0x35E6
MAPIFinderEntryID                         = 0x35E7
let åMAPIContainerFlags                        = 0x3600
let MAPIFolderType                            = 0x3601
let MAPIContentCount                          = 0x3602
let MAPIContentUnread                         = 0x3603
let MAPICreateTemplates                       = 0x3604
let MAPIDetailsTable                          = 0x3605
let MAPISearch                                = 0x3607
let MAPISelectable                            = 0x3609
let MAPISubfolders                            = 0x360A
let MAPIStatus                                = 0x360B
let MAPIAnr                                   = 0x360C
let MAPIContentsSortOrder                     = 0x360D
let MAPIContainerHierarchy                    = 0x360E
let MAPIContainerContents                     = 0x360F
let MAPIFolderAssociatedContents              = 0x3610
let MAPIDefCreateDl                           = 0x3611
let MAPIDefCreateMailuser                     = 0x3612
let MAPIContainerClass                        = 0x3613
let MAPIContainerModifyVersion                = 0x3614
let MAPIAbProviderID                          = 0x3615
let MAPIDefaultViewEntryID                    = 0x3616
let MAPIAssocContentCount                     = 0x3617
let MAPIAttachmentX400Parameters              = 0x3700
let MAPIAttachDataObj                         = 0x3701
let MAPIAttachEncoding                        = 0x3702
let MAPIAttachExtension                       = 0x3703
let MAPIAttachFilename                        = 0x3704
let MAPIAttachMethod                          = 0x3705
let MAPIAttachLongFilename                    = 0x3707
let MAPIAttachPathname                        = 0x3708
let MAPIAttachRendering                       = 0x3709
let MAPIAttachTag                             = 0x370A
let MAPIRenderingPosition                     = 0x370B
let MAPIAttachTransportName                   = 0x370C
let MAPIAttachLongPathname                    = 0x370D
let MAPIAttachMimeTag                         = 0x370E
let MAPIAttachAdditionalInfo                  = 0x370F
let MAPIDisplayType                           = 0x3900
let MAPITemplateID                            = 0x3902
let MAPIPrimaryCapability                     = 0x3904
let MAPI7bitDisplayName                       = 0x39FF
let MAPIAccount                               = 0x3A00
let MAPIAlternateRecipient                    = 0x3A01
let MAPICallbackTelephoneNumber               = 0x3A02
let MAPIConversionProhibited                  = 0x3A03
let MAPIDiscloseRecipients                    = 0x3A04
let MAPIGeneration                            = 0x3A05
let MAPIGivenName                             = 0x3A06
let MAPIGovernmentIDNumber                    = 0x3A07
let MAPIBusinessTelephoneNumber               = 0x3A08
let MAPIHomeTelephoneNumber                   = 0x3A09
let MAPIInitials                              = 0x3A0A
let MAPIKeyword                               = 0x3A0B
let MAPILanguage                              = 0x3A0C
let MAPILocation                              = 0x3A0D
let MAPIMailPermission                        = 0x3A0E
let MAPIMhsCommonName                         = 0x3A0F
let MAPIOrganizationalIDNumber                = 0x3A10
let MAPISurname                               = 0x3A11
let MAPIOriginalEntryID                       = 0x3A12
let MAPIOriginalDisplayName                   = 0x3A13
let MAPIOriginalSearchKey                     = 0x3A14
let MAPIPostalAddress                         = 0x3A15
let MAPICompanyName                           = 0x3A16
let MAPITitle                                 = 0x3A17
let MAPIDepartmentName                        = 0x3A18
let MAPIOfficeLocation                        = 0x3A19
let MAPIPrimaryTelephoneNumber                = 0x3A1A
let MAPIBusiness2TelephoneNumber              = 0x3A1B
let MAPIMobileTelephoneNumber                 = 0x3A1C
let MAPIRadioTelephoneNumber                  = 0x3A1D
let MAPICarTelephoneNumber                    = 0x3A1E
let MAPIOtherTelephoneNumber                  = 0x3A1F
let MAPITransmitableDisplayName               = 0x3A20
let MAPIPagerTelephoneNumber                  = 0x3A21
let MAPIUserCertificate                       = 0x3A22
let MAPIPrimaryFaxNumber                      = 0x3A23
let MAPIBusinessFaxNumber                     = 0x3A24
let MAPIHomeFaxNumber                         = 0x3A25
let MAPICountry                               = 0x3A26
let MAPILocality                              = 0x3A27
let MAPIStateOrProvince                       = 0x3A28
let MAPIStreetAddress                         = 0x3A29
let MAPIPostalCode                            = 0x3A2A
let MAPIPostOfficeBox                         = 0x3A2B
let MAPITelexNumber                           = 0x3A2C
let MAPIIsdnNumber                            = 0x3A2D
let MAPIAssistantTelephoneNumber              = 0x3A2E
let MAPIHome2TelephoneNumber                  = 0x3A2F
let MAPIAssistant                             = 0x3A30
let MAPISendRichInfo                          = 0x3A40
let MAPIWeddingAnniversary                    = 0x3A41
let MAPIBirthday                              = 0x3A42
let MAPIHobbies                               = 0x3A43
let MAPIMiddleName                            = 0x3A44
let MAPIDisplayNamePrefix                     = 0x3A45
let MAPIProfession                            = 0x3A46
let MAPIPreferredByName                       = 0x3A47
let MAPISpouseName                            = 0x3A48
let MAPIComputerNetworkName                   = 0x3A49
let MAPICustomerID                            = 0x3A4A
let MAPITtytddPhoneNumber                     = 0x3A4B
let MAPIFtpSite                               = 0x3A4C
let MAPIGender                                = 0x3A4D
let MAPIManagerName                           = 0x3A4E
let MAPINickname                              = 0x3A4F
let MAPIPersonalHomePage                      = 0x3A50
let MAPIBusinessHomePage                      = 0x3A51
let MAPIContactVersion                        = 0x3A52
let MAPIContactEntryids                       = 0x3A53
let MAPIContactAddrtypes                      = 0x3A54
let MAPIContactDefaultAddressIndex            = 0x3A55
let MAPIContactEmailAddresses                 = 0x3A56
let MAPICompanyMainPhoneNumber                = 0x3A57
let MAPIChildrensNames                        = 0x3A58
let MAPIHomeAddressCity                       = 0x3A59
let MAPIHomeAddressCountry                    = 0x3A5A
let MAPIHomeAddressPostalCode                 = 0x3A5B
let MAPIHomeAddressStateOrProvince            = 0x3A5C
let MAPIHomeAddressStreet                     = 0x3A5D
let MAPIHomeAddressPostOfficeBox              = 0x3A5E
let MAPIOtherAddressCity                      = 0x3A5F
let MAPIOtherAddressCountry                   = 0x3A60
let MAPIOtherAddressPostalCode                = 0x3A61
let MAPIOtherAddressStateOrProvince           = 0x3A62
let MAPIOtherAddressStreet                    = 0x3A63
let MAPIOtherAddressPostOfficeBox             = 0x3A64
let MAPIStoreProviders                        = 0x3D00
let MAPIAbProviders                           = 0x3D01
let MAPITransportProviders                    = 0x3D02
let MAPIDefaultProfile                        = 0x3D04
let MAPIAbSearchPath                          = 0x3D05
let MAPIAbDefaultDir                          = 0x3D06
let MAPIAbDefaultPab                          = 0x3D07
let MAPIFilteringHooks                        = 0x3D08
let MAPIServiceName                           = 0x3D09
let MAPIServiceDllName                        = 0x3D0A
let MAPIServiceEntryName                      = 0x3D0B
let MAPIServiceUID                            = 0x3D0C
let MAPIServiceExtraUids                      = 0x3D0D
let MAPIServices                              = 0x3D0E
let MAPIServiceSupportFiles                   = 0x3D0F
let MAPIServiceDeleteFiles                    = 0x3D10
let MAPIAbSearchPathUpdate                    = 0x3D11
let MAPIProfileName                           = 0x3D12
let MAPIIdentityDisplay                       = 0x3E00
let MAPIIdentityEntryID                       = 0x3E01
let MAPIResourceMethods                       = 0x3E02
let MAPIResourceType                          = 0x3E03
let MAPIStatusCode                            = 0x3E04
let MAPIIdentitySearchKey                     = 0x3E05
let MAPIOwnStoreEntryID                       = 0x3E06
let MAPIResourcePath                          = 0x3E07
let MAPIStatusString                          = 0x3E08
let MAPIX400DeferredDeliveryCancel            = 0x3E09
let MAPIHeaderFolderEntryID                   = 0x3E0A
let MAPIRemoteProgress                        = 0x3E0B
let MAPIRemoteProgressText                    = 0x3E0C
let MAPIRemoteValidateOk                      = 0x3E0D
let MAPIControlFlags                          = 0x3F00
let MAPIControlStructure                      = 0x3F01
let MAPIControlType                           = 0x3F02
let MAPIDeltax                                = 0x3F03
let MAPIDeltay                                = 0x3F04
let MAPIXpos                                  = 0x3F05
let MAPIYpos                                  = 0x3F06
let MAPIControlID                             = 0x3F07
let MAPIInitialDetailsPane                    = 0x3F08
let MAPIIdSecureMin                           = 0x67F0
let MAPIIdSecureMax                           = 0x67FF
